soundcloud:
  - title : Mauvaise copie
    url : https://soundcloud.com/leskrapos/sets/mauvaise-copie
    artwork : mauvaise_copie.jpg
    year : 2019
  - title : Love @NewMorning
      url : https://soundcloud.com/leskrapos/sets/love-newmorning
      artwork : new_morning.jpg
      year : 2016
  - title : Mauvaise copie
      url : https://soundcloud.com/leskrapos/sets/interdits-de-gymnase
      artwork : interdits_gymnase.jpg
      year : 2010    
youtube:
  - tune : Toccata
    reference : Fanfa'Rhône 2021
    url : https://youtu.be/X9S5LUO_yD8
    artwork : toccata.jpg
  - tune : Medley Daft Punk
    reference : Fanfa'Rhône 2021
    url : https://youtu.be/PmUCXIE-QrU
    artwork : daftpunk.jpg
regions :
  - ARA : Auvergne-Rhône-Alpes
  - BFC : Bourgogne-Franche-Comté
  - BRE : Bretagne
  - COR : Corse
  - CVL : Centre-Val de Loire
  - GES : Grand Est
  - HDF : Hauts-de-France
  - IDF :	Île-de-France
  - NAQ	: Nouvelle-Aquitaine
  - NOR :	Normandie
  - OCC :	Occitanie
  - PAC	: Provence-Alpes-Côte d'Azur
  - PDL :	Pays de la Loire
  - WLD : Ailleurs dans le monde ...
friends:
#Pas pu mettre les zouzes, pas trouvé de page FB
#Je les ai rangés par régions, plus facile pour gérer l'ordre : le site les affiche dans l'ordre où ils arrivent, du coup on mettre ceux qu'on aime le plus avant ;)
  - band : La Pustule
    baseline : La fanfare qui décapsule
    region : ARA
    location : Lyon
    logo : pustule
    url : https://pustule.org
  - band : LGMX
    baseline : Fanfare psychoactive électrostimulante
    region : ARA
    location : Lyon
    logo : lgmx
    url : https://www.lgmx.fr
  - band : Super Smash Brass
    baseline : Fanfare jeux vidéos
    region : ARA
    location : Lyon
    logo : ssb
    url : http://supersmashbrass.com
   - band : Kärlek
    baseline : Reprises Black-Death-Thrash
    region : ARA
    location : Lyon
    logo : karlek
    url : https://www.facebook.com/fanfarekarlek/
  - band : La Fanfat'
    baseline : La seule fanfare 100% matière grasse. Mais avec des paillettes.
    region : ARA
    location : Lyon
    logo : fanfat
    url : https://www.facebook.com/lafanfat/
   - band : Over Ze Knup
    baseline : Classic & Rock'n'Roll Quatuor sauce Punk'Jazz
    region : ARA
    location : Lyon
    logo : over_ze_knup
    url : https://overzeuknup.top
   - band : Fat Ducks
    baseline : Jeune fanfare énergique aux rythmes de funk et d'électro
    region : ARA
    location : Lyon
    logo : fat_ducks
    url : https://www.facebook.com/profile.php?id=100076116732441
  - band : Canal Chips
    baseline : Fanfare festive en Drôme-Ardèche
    region : ARA
    location : Valence
    logo : canal_chips
    url : https://canalchips.wixsite.com/chips
  - band : Marcel Frontale
    baseline : Fanfare New Orleans
    region : ARA
    location : Lyon
    logo : marcel_frontale
    url : https://www.facebook.com/MarcelFrontale
  - band : Velcro’s Brass Band
    baseline : Musique survitaminée
    region : ARA
    location : Lyon
    logo : velcros
    url : https://www.facebook.com/velcrosbrassband/
  - band : La Cacophonie
    baseline : Fanfare presqu'écoutable
    region : ARA
    location : Lyon
    logo : cacophonie
    url : http://www.fanfare-cacophonie.org
  - band : Pink It Black
    baseline : La fanfare en rose et noir
    region : ARA
    location : Grenoble
    logo : pink_it_black
    url : https://pinkitblack.fr/
  - band : 38 tonnes
    baseline : 
    region : ARA
    location : Grenoble
    logo : 38_tonnes
    url : https://www.38tonnes.fr
  - band : La Mort Subite
    baseline : 
    region : ARA
    location : Grenoble
    logo : mort_subite
    url : https://bandlamortsubite.wixsite.com/band-lamortsubite
  - band : Les garces embouchées
    baseline : 
    region : ARA
    location : Grenobles
    logo : garces_emouchees
    url : http://garcesembouchees.canalblog.com/
  - band : Elan Brass Band
    baseline : 
    region : BFC
    location : Toucy
    logo : elan_brass_band
    url : http://www.elanbrassband.org
  - band : La Banda Freux
    baseline : La fanfare la plus à l'ouest
    region : BRE
    location : Brest
    logo : banda_feux
    url : https://www.facebook.com/profile.php?id=100062927544086
  - band : A Bout de Souffle
    baseline : 
    region : BRE
    location : Douarnenez
    logo : a_bout_de_souffle
    url : http://aboutdesouffle.free.fr
  - band : Zebaliz
    baseline : Joyeuse fanfare
    region : BRE
    location : Brest
    logo : zebaliz
    url : http://fanfare-zebaliz.com/home.php3
  - band : La Vaginale
    baseline :
    region : CVL
    location : Tours
    logo : la_vaginale
    url : https://www.facebook.com/BrassUnitedSC/
  - band : FEIS
    baseline : Fanfare des Externes et Internes de Strasbourg
    region : GES
    location : Strasbourg
    logo : feis
    url : https://www.facebook.com/BrassUnitedSC/
  - band : Fanfare Tractopelle
    baseline : Groupe rétro-futuriste
    region : HDF
    location : Lille
    logo : tractopelle
    url : http://www.fanfaretractopelle.fr
  - band : La Brigade des Tubes
    baseline : 
    region : HDF
    location : Lille
    logo : brigade_des_tubes
    url : http://www.labrigadedestubes.com
  - band : 3615 Brass Band
    baseline : Fanfare bas débit
    region : IDF
    location : Paris
    logo : 3615
    url : https://3615bb.com
  - band : Rolland Merguez
    baseline : Fanfare cosmique
    region : IDF
    location : Paris
    logo : rolland_merguez
    url : http://rollandmerguez.fr
  - band : Dumb and Brass
    baseline : Fanfare psycho-Caraïbes-Electro-Funk-Reggae
    region : IDF
    location : Paris
    logo : dumb_and_brass
    url : http://www.dumbandbrass.com
  - band : Mouette et Charbons
    baseline : 
    region : IDF
    location : Paris
    logo : mouette_et_charbons
    url : https://mouetteetcharbons.tumblr.com
  - band : Les lapins superstars
    baseline : 
    region : IDF
    location : Paris
    logo : lapins_superstars
    url : https://www.facebook.com/leslapinsuperstars/
  - band : La voiture 4
    baseline : 
    region : IDF
    location : Paris
    logo : voiture_4
    url : http://voiture4.free.fr
  - band : SuperTromp
    baseline : Fanfare Powwwerrrrr! et de qualité
    region : IDF
    location : Paris
    logo : supertromp
    url : https://www.facebook.com/FanfareSupertromp/
  - band : Les Zôtres
    baseline : Fanfare Indirigeable
    region : IDF
    location : Paris
    logo : les_zotres
    url : https://www.facebook.com/leszotres.fanfare/?locale=fr_FR
  - band : Bindy Nasty
    baseline : 
    region : IDF
    location : Paris
    logo : bindy_nasty 
    url : https://bindinasty.wixsite.com/bindi
  - band : Tabatakash
    baseline : 
    region : IDF
    location : Paris
    logo : tabatakash
    url : https://tabatakashfanfare.wixsite.com/tabatakash
  - band : Godfingers
    baseline : 
    region : IDF
    location : Paris
    logo : godfingers
    url : https://www.godfingers.com
  - band : Poil O'Brass Band
    baseline : Fanfare ébouriffante à la bonne humeur duveteuse
    region : IDF
    location : Paris
    logo : poilobrassband
    url : https://www.facebook.com/Poilobrass/
  - band : Les Gratkipoils
    baseline : La fanfare qui démange
    region : IDF
    location : Paris
    logo : gratkipoils
    url : http://gratkipoils.free.fr
  - band : Les Monty Pistons
    baseline : 
    region : IDF
    location : Paris
    logo : monty_pistons
    url : https://www.facebook.com/fanfareMonty/
  - band : 404 Bonheur
    baseline : 
    region : IDF
    location : Paris
    logo : 404_bonheur
    url : https://www.facebook.com/404bonheur/
  - band : Les muses tanguent
    baseline : 
    region : IDF
    location : Paris
    logo : muse_tanguent
    url : https://www.facebook.com/profile.php?id=100063747243051
  - band : La Grasse Bande
    baseline : 
    region : NAQ
    location : Bordeaux
    logo : la_grasse_bande
    url : https://lagrassebande.fr
  - band : Los Teoporos
    baseline : Tzigani Funky !
    region : NAQ
    location : Bordeaux
    logo : los_teoporos
    url : https://www.facebook.com/fanfarelosteoporos
  - band : Los Arsouillos
    baseline : 
    region : NAQ
    location : Aire sur l'Adour
    logo : los_arsouillos
    url : https://www.arsouillos.com
  - band : Le Beat Cheese
    baseline : Fanfare affinée
    region : NAQ
    location : Bordeaux
    logo : le_beat_cheese
    url : https://fanfarelebeatcheese.fr
  - band : Brigitte Bordo
    baseline : 
    region : NAQ
    location : Bordeaux
    logo : brigitte_bordo
    url : https://brigitte-bordo.com
  - band : Les P'tits Culs Ivres
    baseline : Fanfare de type brass band britannico-New-Orleans
    region : NAQ
    location : Limoges
    logo : les_ptits_culs_ivres
    url : https://www.facebook.com/LesPtitsCulsIvres
  - band : L'Etoile Cirée
    baseline : 
    region : NOR
    location : Grandvill
    logo : letoile_ciree
    url : https://www.facebook.com/fanfare.etoile.ciree
  - band : La Vashfol
    baseline : 
    region : NOR
    location : Rouen
    logo : la_vashfol
    url : https://www.vashfol.fr
  - band : Les Kadors 
    baseline : La fanfare des jusqu'au-boutistes
    region : OCC
    location : Montpellier
    logo : les_kadors
    url : http://www.fanfaredeskadors.com
  - band : Lady Jaja
    baseline : Fanfare féminine et oenophile
    region : OCC
    location : Nîmes
    logo : lady_jaja
    url : https://fanfareladyjaja.wordpress.com
  - band : Les judas
    baseline : Fanfare iconoblaste
    region : OCC
    location : Aimargues
    logo : les_judas
    url : https://www.facebook.com/LesJudas
  - band : Les Peillasses
    baseline : 
    region : OCC
    location : Nîmes
    logo : les_peillasses
    url : https://www.facebook.com/fanfare.lespeillasses/?locale=fr_FR
  - band : Attila et Huns II, III, IV
    baseline : 
    region : OCC
    location : St Etienne d'Escattes
    logo : attila
    url : https://fanfareattila.wixsite.com/home
  - band : Les Trous Balourds
    baseline : Fanfare ambidextre Polymorphe
    region : OCC
    location : Toulouse
    logo : les_trous_balours
    url : https://collectif-fanfarnaum.fr/trous-balourds/
  - band : Coco Fanfare Club
    baseline : Fanfare tout terrain
    region : OCC
    location : Montpellier
    logo : coco_fanfare_club
    url : https://cocofanfareclub.fr
  - band : La mécanique des Cuivres
    baseline : 
    region : OCC
    location : Toulouse
    logo : mecanique_des_cuivres
    url : https://collectif-fanfarnaum.fr/la-mecanique-des-cuivres/
  - band : Le Pompier Poney Club
    baseline : Fanfare hyperactive
    region : PAC
    location : Marseille
    logo : ppc
    url : https://www.lepompierponeyclub.com
  - band : Mamie Vortex
    baseline : La fanfare riche en Oméga Teuf !
    region : PAC
    location : Marseille
    logo : mamie_vortex
    url : https://www.facebook.com/mamievortex/
  - band : Mudanza
    baseline : La fanfare qui déménage
    region : PAC
    location : Salon de provence
    logo : mudanza
    url : https://mudanza.fr
  - band : Les Trompettes de Fallope
    baseline : La fanfare qui prend soin de vous
    region : PDL
    location : Nantes
    logo : trompettes_de_falloppe 
    url : https://trompettesdefallope.com
  - band : Terminus Brass Band
    baseline : 
    region : PDL
    location : Nantes
    logo : terminus
    url : https://www.facebook.com/terminusbrassband/
  - band : Les Roller Toaster
    baseline : Fanfare du futur
    region : PDL
    location : Nantes
    logo : roller_toaster
    url : https://www.facebook.com/FanfareRollerToaster/
  - band : Les WestCostars
    baseline : Fanfare Bam bam
    region : PDL
    location : Nantes
    logo : westcostars
    url : https://www.facebook.com/WestCostars/
  - band : Mefisto Brass
    baseline : Live techno brass attitude
    region : WLD
    location : Milan, Italie
    logo : mefisto
    url : https://www.facebook.com/mefistobrass/
  - band : Dirty Athens Brass Band
    baseline : 
    region : WLD
    location : Athènes, Gèce
    logo : dirty_athens
    url : https://www.facebook.com/dirtyathensbrassband
  - band : Brass United Social Club
    baseline : The funk-led brassy supergroup you never knew you needed
    region : WLD
    location : Londres, Angleterre
    logo : busc
    url : https://www.facebook.com/BrassUnitedSC/

    